[package]
name = "pacaptr"
version = "0.17.2"
edition = "2021"
license = "GPL-3.0"

authors = ["Rami3L <rami3l@outlook.com>"]
homepage = "https://github.com/rami3l/pacaptr"
repository = "https://github.com/rami3l/pacaptr"
description = "Pacman-like syntax wrapper for many package managers."
readme = "README.md"

keywords = ["package-management"]
categories = ["command-line-utilities"]

include = ["LICENSE", "Cargo.toml", "src/**/*.rs", "build.rs"]
exclude = ["dist/**/*", "docs/**/*"]
# build = "build.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
built = { version = "0.6.0", features = ["git2"] }

[dev-dependencies]
xshell = "0.2.3"

[dependencies]
async-trait = "0.1.65"
bytes = "1.4.0"
clap = { version = "4.1.8", features = ["cargo", "derive"] }
confy = "0.5.1"
console = "0.15.5"
dialoguer = { version = "0.10.3", features = ["fuzzy-select"] }
dirs-next = "2.0.0"
futures = { version = "0.3.26", default-features = false, features = ["std"] }
indoc = "2.0.0"
is-root = "0.1.2"
itertools = "0.10.5"
macro_rules_attribute = "0.1.3"
once_cell = "1.17.1"
pacaptr-macros = { path = "crates/pacaptr-macros", version = "0.17.0" }
paste = "1.0.11"
regex = { version = "1.7.1", default-features = false, features = [
  "std",
  "perf",
  "unicode-perl",
] }
serde = { version = "1.0.152", features = ["derive"] }
tap = "1.0.1"
thiserror = "1.0.38"
tokio = { version = "1.26.0", features = [
  "io-std",
  "io-util",
  "macros",
  "process",
  "rt-multi-thread",
  "sync",
] }
tokio-stream = "0.1.12"
tokio-util = { version = "0.7.7", features = ["codec", "compat"] }
tt-call = "1.0.9"
which = "4.4.0"

[package.metadata.deb]
copyright = "2020, Rami3L"
maintainer = "Rami3L <rami3l@outlook.com>"
# license-file = ["LICENSE", "4"]
assets = [
  [
    "target/release/pacaptr",
    "usr/bin/",
    "755",
  ],
  [
    "README.md",
    "usr/share/doc/pacaptr/README",
    "644",
  ],
]
depends = "$auto"
extended-description = """\
A Rust port of icy/pacapt, a wrapper for many package managers with \
pacman-style command syntax."""
priority = "optional"
section = "utility"

[workspace]
members = [".", "xtask", "crates/*"]

[profile.release]
codegen-units = 1
debug = 0
lto = true
opt-level = "z"
panic = "abort"
strip = "symbols"
