# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "pacaptr"
version = "0.19.2"
edition = "2021"
license = "GPL-3.0"

authors = ["Rami3L <rami3l@outlook.com>"]
homepage = "https://github.com/rami3l/pacaptr"
repository = "https://github.com/rami3l/pacaptr"
description = "Pacman-like syntax wrapper for many package managers."
readme = "README.md"

keywords = ["package-management"]
categories = ["command-line-utilities"]

include = ["LICENSE", "Cargo.toml", "src/**/*.rs", "build.rs"]
# exclude = ["dist/**/*", "docs/**/*"]
# build = "build.rs"

[package.metadata.docs.rs]
all-features = true

[package.metadata.deb]
copyright = "2020, Rami3L"
maintainer = "Rami3L <rami3l@outlook.com>"
# license-file = ["LICENSE", "4"]
assets = [
  [
    "target/release/pacaptr",
    "usr/bin/",
    "755",
  ],
  [
    "README.md",
    "usr/share/doc/pacaptr/README",
    "644",
  ],
]
depends = "$auto"
extended-description = "Pacman-like syntax wrapper for many package managers."
priority = "optional"
section = "utility"

[workspace]
members = [".", "crates/*"]

[build-dependencies]
built = { version = "0.6.1", features = ["git2"] }

[dev-dependencies]
xshell = "0.2.5"

[dependencies]
async-trait = "0.1.73"
bytes = "1.4.0"
clap = { version = "4.3.21", features = ["cargo", "derive"] }
console = "0.15.7"
dialoguer = { version = "0.10.4", features = ["fuzzy-select"] }
dirs-next = "2.0.0"
figment = { version = "0.10.10", features = ["env", "toml"] }
futures = { version = "0.3.28", default-features = false, features = ["std"] }
indoc = "2.0.3"
is-root = "0.1.3"
itertools = "0.11.0"
macro_rules_attribute = "0.2.0"
once_cell = "1.18.0"
pacaptr-macros = { path = "crates/pacaptr-macros", version = "0.19.0" }
paste = "1.0.14"
regex = { version = "1.9.3", default-features = false, features = [
  "std",
  "perf",
  "unicode-case",
  "unicode-perl",
] }
serde = { version = "1.0.183", features = ["derive"] }
tap = "1.0.1"
thiserror = "1.0.46"
tokio = { version = "1.31.0", features = [
  "io-std",
  "io-util",
  "macros",
  "process",
  "rt-multi-thread",
  "sync",
] }
tokio-stream = "0.1.14"
tokio-util = { version = "0.7.8", features = ["codec", "compat"] }
tt-call = "1.0.9"
which = "4.4.0"

[features]
docs = []
test = []

[profile.release]
codegen-units = 1
debug = 0
lto = true
opt-level = "z"
panic = "abort"
strip = "symbols"

# https://github.com/pksunkara/cargo-workspaces/tree/master#config
[workspace.metadata.workspaces]
no_individual_tags = true
