[package]
name = "pacaptr"
version = "0.16.1"
edition = "2021"
license = "GPL-3.0"

authors = ["Rami3L <rami3l@outlook.com>"]
homepage = "https://github.com/rami3l/pacaptr"
repository = "https://github.com/rami3l/pacaptr"
description = "Pacman-like syntax wrapper for many package managers."
readme = "README.md"

keywords = ["package-management"]
categories = ["command-line-utilities"]

include = ["LICENSE", "Cargo.toml", "src/**/*.rs", "build.rs"]
exclude = ["dist/**/*", "docs/**/*"]
# build = "build.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [build-dependencies]

[dev-dependencies]
xshell = "0.2.2"

[dependencies]
async-trait = "0.1.57"
bytes = "1.2.1"
clap = { version = "4.0.8", features = ["cargo", "derive"] }
confy = "0.5.0"
console = "0.15.2"
dialoguer = { version = "0.10.2", features = ["fuzzy-select"] }
dirs-next = "2.0.0"
futures = { version = "0.3.24", default-features = false, features = ["std"] }
indoc = "1.0.7"
is-root = "0.1.2"
itertools = "0.10.5"
macro_rules_attribute = "0.1.2"
once_cell = "1.15.0"
pacaptr-macros = { path = "crates/pacaptr-macros", version = "0.16.1" }
paste = "1.0.9"
regex = { version = "1.6.0", default-features = false, features = [
  "std",
  "perf",
  "unicode-perl",
] }
serde = { version = "1.0.145", features = ["derive"] }
tap = "1.0.1"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = [
  "io-std",
  "io-util",
  "macros",
  "process",
  "rt-multi-thread",
  "sync",
] }
tokio-stream = "0.1.10"
tokio-util = { version = "0.7.4", features = ["codec", "compat"] }
tt-call = "1.0.8"
which = "4.3.0"

[package.metadata.deb]
copyright = "2020, Rami3L"
maintainer = "Rami3L <rami3l@outlook.com>"
# license-file = ["LICENSE", "4"]
assets = [
  [
    "target/release/pacaptr",
    "usr/bin/",
    "755",
  ],
  [
    "README.md",
    "usr/share/doc/pacaptr/README",
    "644",
  ],
]
depends = "$auto"
extended-description = """\
A Rust port of icy/pacapt, a wrapper for many package managers with \
pacman-style command syntax."""
priority = "optional"
section = "utility"

[workspace]
members = [".", "xtask", "crates/*"]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
codegen-units = 1
debug = 0
lto = true
opt-level = "z"
panic = "abort"
strip = "symbols"
