edition = "2024"
unstable_features = true

format_macro_matchers = true
format_macro_bodies = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_impl_items = true
wrap_comments = true

use_field_init_shorthand = true
trailing_semicolon = true
