[package]
name = "pacaptr-macros"
version = "0.19.2"
edition = "2021"
license = "GPL-3.0"

authors = ["Rami3L <rami3l@outlook.com>"]
homepage = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
repository = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
description = "Implementation of several macros used in pacaptr."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.74"
itertools = "0.11.0"
litrs = "0.4.0"
once_cell = "1.18.0"
proc-macro2 = "1.0.66"
quote = "1.0.32"
regex = "1.9.3"
syn = "2.0.28"
tabled = "0.14.0"
