[package]
name = "pacaptr-macros"
version = "0.20.0"
license.workspace = true
edition.workspace = true

homepage = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
repository = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
description = "Implementation of several macros used in pacaptr."

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.75"
itertools = "0.11.0"
litrs = "0.4.1"
once_cell = "1.18.0"
proc-macro2 = "1.0.69"
quote = "1.0.33"
regex = "1.10.2"
syn = "2.0.39"
tabled = "0.14.0"
