[package]
name = "pacaptr-macros"
version = "0.20.1"
license.workspace = true
edition.workspace = true

homepage = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
repository = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
description = "Implementation of several macros used in pacaptr."

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.78"
itertools = "0.12.0"
litrs = "0.4.1"
once_cell = "1.19.0"
proc-macro2 = "1.0.70"
quote = "1.0.34"
regex = "1.10.2"
syn = "2.0.42"
tabled = "0.15.0"

[lints]
workspace = true
