[package]
name = "pacaptr-macros"
version = "0.16.1"
edition = "2021"
license = "GPL-3.0"

authors = ["Rami3L <rami3l@outlook.com>"]
homepage = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
repository = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
description = "Implementation of several macros used in pacaptr."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.65"
itertools = "0.10.5"
litrs = "0.2.3"
once_cell = "1.15.0"
proc-macro2 = "1.0.45"
quote = "1.0.21"
regex = "1.6.0"
syn = "1.0.101"
tabled = "0.8.0"
