[package]
name = "pacaptr-macros"
version = "0.17.1"
edition = "2021"
license = "GPL-3.0"

authors = ["Rami3L <rami3l@outlook.com>"]
homepage = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
repository = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
description = "Implementation of several macros used in pacaptr."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.69"
itertools = "0.10.5"
litrs = "0.3.0"
once_cell = "1.17.1"
proc-macro2 = "1.0.51"
quote = "1.0.23"
regex = "1.7.1"
syn = "1.0.107"
tabled = "0.10.0"
