[package]
name = "pacaptr-macros"
version = "0.21.0"
license.workspace = true
edition.workspace = true

homepage = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
repository = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
description = "Implementation of several macros used in pacaptr."

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.79"
itertools = "0.12.1"
litrs = "0.4.1"
once_cell = "1.19.0"
proc-macro2 = "1.0.78"
quote = "1.0.35"
regex = "1.10.3"
syn = "2.0.48"
tabled = "0.15.0"

[lints]
workspace = true
