[package]
name = "pacaptr-macros"
version = "0.13.2"
edition = "2021"
license = "GPL-3.0"

authors = ["Rami3L <rami3l@outlook.com>"]
homepage = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
repository = "https://github.com/rami3l/pacaptr/tree/master/crates/pacaptr-macros"
description = "Implementation of several macros used in pacaptr."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.53"
itertools = "0.10.3"
litrs = "0.2.3"
once_cell = "1.9.0"
proc-macro2 = "1.0.36"
quote = "1.0.15"
regex = "1.5.4"
syn = "1.0.86"
tabled = "0.5.0"
