name: dependabot-auto-merge

on:
  # https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Hack: https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/58#issuecomment-981520187
          token: ${{ secrets.TAP_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{ secrets.TAP_GITHUB_TOKEN }}
