name: publish

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  create-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: ${{ contains(github.ref, '-') }}

  publish:
    name: Publish for ${{ matrix.os }}
    needs: [create-release]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            # artifact_name: pacaptr.exe
            # asset_name: pacaptr-windows-amd64
          - os: macos-latest
            # artifact_name: pacaptr
            # asset_name: pacaptr-macos-amd64
          - os: ubuntu-latest
            # artifact_name: pacaptr
            # asset_name: pacaptr-linux-amd64
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Set macOS environment variables
        if: runner.os == 'macOS'
        run: |
          echo "SDKROOT=$(xcrun -sdk macosx11.1 --show-sdk-path)" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.1 --show-sdk-platform-version)" >> $GITHUB_ENV
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cargo xtask publish

  bump-choco-version:
    name: Publish app on Chocolatey
    runs-on: windows-latest
    needs: [publish]
    if: ${{ !contains(github.ref, '-') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish to choco
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: cargo xtask bump-choco

  bump-tap-version:
    name: Bump formula version for homebrew
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current tag
        uses: olegtarasov/get-tag@v2.1
        id: get_tag
      - name: Generate new formula as `pacaptr.rb`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cargo xtask bump-tap
      - name: Checkout tap
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
          repository: rami3l/homebrew-tap
          path: homebrew-tap
      - name: Overwrite formula
        run: |
          cp ./pacaptr.rb homebrew-tap/pacaptr.rb
          ls homebrew-tap
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          path: homebrew-tap
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
          title: "feat: add `pacaptr` ${{ steps.get_tag.outputs.tag }}"
          commit-message: "feat: add `pacaptr` ${{ steps.get_tag.outputs.tag }}"
